config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "produtos#index"
  
  post "/produtos/response_json" => "produtos#response_json"

  resources :produtos do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :produto
  enum classificacao: { 'Like' => 0, 'Deslike' => 1 }

  enum status:  { 'Public' => 0, 'Private' => 2, 'Archived' => 3 }

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['Public' , 'Private', 'Archived']

  VALID_CATEGORIA = ['Camisetas' => 0, 'Saias' => 1, 'Vestidos' => 2, 'Body' => 3, 'Cropped' => 4, 'Blusas' => 5, 'Calças' => 6, 'Shorts' => 7, 'Macacão' => 8]

  # included do
  #   validates :status, inclusion: { in: VALID_STATUSES }
  # end

  class_methods do
    def public_count
      where(status: 'Public').count
    end
  end

  def archived?
    status == 'Archived'
  end
end
  

app/models/produto.rb
class Produto < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy

  mount_uploader :image, FileUploader

  # Validacoes
  validates :codigo, presence: true, length: { minimum: 1}
  validates :nome, presence: true, length: { minimum: 9}
  validates :classificacao, presence: true, length: { minimum: 2}
  validates :descricao, presence: true, length: { minimum: 10}
  validates :categoria, presence: true, length: { minimum: 1}
  #validates :valor, presence: true, length: { minimum: 1}
  
  enum classificacao: { 
    'Produto' => 0,
    'Servico' => 1
  }

  enum status: { 
    'Public' => 0,
    'Private' => 1,
    'Archived' => 2
  }
  
  enum categoria: { 
    'Camisetas' => 0,
    'Saias' => 1, 
    'Vestidos' => 2,
    'Body' => 3,
    'Cropped' => 4,
    'Blusas' => 5, 
    'Calças' => 6,
    'Shorts' => 7,
    'Macacão' => 8
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @produtos = Produto.find(params[:produto_id])
    @comment = @produtos.comments.create(comment_params)
    redirect_to produto_path(@produtos) 
  end

  def destroy
    @produtos = Produto.find(params[:produto_id])
    @comment = @produtos.comments.find(params[:id])
    @comment.destroy
    redirect_to produto_path(@produtos)
  end
  

  private

  def comment_params
    params.require(:comment).permit(:commenter, :classificacao, :status)
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @q = Produto.ransack(params[:q])
    @produtos = @q.result(distinct: true).includes(:comments)
  end

  def response_json
    @produto = Produto.new(produto_params) 

    respond_to do |format|
      #render json: JSON.pretty_generate(@produtos.as_json)
      if @produto.save
        format.json { render json: @produto }
      else
        format.json { render :json => @produto.errors }
      end
    end
  end

  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @produto }
    end
  end
  
  def new
    @produto = Produto.new
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|

      if @produto.save
        format.js { redirect_to produtos_url }
      else
        format.js { render :new }
      end
      format.html
      format.json { render json: @produto }
    end
  end

  def edit
    @produto =  Produto.find(params[:id]) 
    respond_to do |format|
      format.js
    end   
  end

  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|

      if @produto.update_attributes(produto_params)
        format.js { redirect_to produtos_url }
      else
        format.js { render :edit }
      end
      format.html
      format.json { head :ok }
    end
  end

  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy
    redirect_to root_path

    respond_to do |format|
      format.html
      format.json { head :ok }
    end

  end
  
  private

  def produto_params
    params.require(:produto).permit(:codigo, :nome, :classificacao, :descricao, :status, :categoria, :valor, :image )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/comments/_comment.html.erb
<div class="text-white pt-2">
  <% produto.comments.each do |comment| %>
    <% if comment.valid? %>
      <div>
        <strong>Autor do comentário:</strong>
        <%= comment.commenter %>
      </div>

      <div>
        <strong>Comentário:</strong>
        <%= comment.classificacao %>
      </div>
      <br/>
    <% end %>
    <%= link_to 'Apagar comentário', [comment.produto, comment], class: "btn btn-secondary",
                  method: :delete,
                  data: { confirm: "Tem Certeza?" } %>

  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@produto, Comment.new], html: {class: "produto_search" } do |f| %>
  <div class="row">
    <div class="col-lg-12">
      <%= f.label 'Comentário', class: 'text-white' %>
      <%= f.text_area :commenter, class: 'form-control' %><br/>
    </div>
    
    <div class="form-group col-md-5">
      <%= f.label :classificacao, class: 'text-white' %>
      <%= f.select :classificacao, Comment.classificacaos.keys.to_a, {}, class: "form-control" %>
    </div>

    <div class="form-group col-md-5">
      <%= f.label :status, class: 'text-white'%><br/>
      <%= f.select :status, Comment.statuses.keys.to_a, {}, class: "form-control" %>
    </div>
    <br/>
  </div>
  <br/>
  <br/>  
  <%= f.submit "Criar Comentario", class: "btn btn-primary text-white" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RGaldino</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  
  <body> 
    <%= video_tag( # adicionar o video na tela
        'girl.mp4',
        id: 'background',
        autoplay: true,
        loop: true,
        muted: true
      ) 
    %>

    <%= render 'shared/nav' %>
     <div class="container">
    <%= yield %>
    <%= render 'shared/footer' %>    
    </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<div class="box-shadow-z1 padding-lg border-radius row margin-sm">
  <%= form_for @produto, remote: true, html: { class: 'form-horizontal' } do |f| %>
    <%= params[:action].eql?("edit") ? "Editar " : "Novo Produto" %>
    <% if @produto.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@produto.errors.count, "error") %> Nao possibilitou salvamento do produto :</h2>
        <ul>
          <% @produto.errors.full_messages_for(:nome).each do |message| %>
            <li><%= message %></li>
          <% end %>
          <% @produto.errors.full_messages_for(:codigo).each do |message| %>
            <li><%= message %></li>
          <% end %>
          <% @produto.errors.full_messages_for(:descricao).each do |message| %>
            <li><%= message %></li>
          <% end %>
          <% @produto.errors.full_messages_for(:classificacao).each do |message| %>
            <li><%= message %></li>
          <% end %>
          <%= @produto.errors.full_messages_for(:categoria).each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="col-lg-3">
      <%= f.label :codigo %><br />
      <%= f.text_field :codigo, class: "form-control" %>
      <% @produto.errors.full_messages_for(:codigo).each do |message| %>
        <div> <%= message %> </div>
      <% end %>
    </div>

    <div class="col-lg-3" >
      <%= f.label :valor %>
      <%= f.text_field :valor, class: "form-control" %><br />
    </div>

    <div class="col-lg-6">
      <%= f.label :nome %><br />
      <%= f.text_field :nome, class: "form-control"  %><br />
      <% @produto.errors.full_messages_for(:nome).each do |message|  %>
        <div> <%= message %> </div>
      <% end %>
    </div>
   
    <div class="col-lg-6">
      <%= f.label :descricao %><br />
      <%= f.text_area :descricao, class: "form-control"  %><br />
      <% @produto.errors.full_messages_for(:descricao).each do |message| %>
        <div> <%= message %> </div>
      <% end %>
    </div>
    
    <div class="row">
      <div class="form-group col-md-3">
        <%= f.label :classificacao %><br />
        <%= f.select :classificacao, Produto.classificacaos.keys.to_a, {}, class: "form-control" %>
        <% @produto.errors.full_messages_for(:classificacao).each do |message| %>
          <div> <%= message %> </div>
        <% end %>
      </div>
      
      <div class="form-group col-md-3">
        <%= f.label :status %>
        <%= f.select :status, Produto.statuses.keys.to_a, {}, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= f.label :categoria %>
        <%= f.select :categoria, Produto.categoria.keys.to_a, {}, class: "form-control" %>
        <% @produto.errors.full_messages_for(:categoria).each do |message| %>
          <div> <%= message %> </div>
        <% end %>
      </div>
    </div>  
    <br/>
    <div class="form-group col-md-12">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <br/>
    <div>
      <%= f.submit "Criar", class: "btn btn-secondary"%>
      <%= link_to 'Back', produtos_url, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>  

app/views/produtos/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/produtos/_search_form.html.erb
<br/>
<%= search_form_for @q, html: {class: "produto_search" } do |f|  %>
  <div class="row">
    <div class="col-lg-3">
      <%= f.label :nome, class: 'text-white' %>
      <%= f.search_field :nome_cont, class: 'form-control'%>
    </div>

    <div class="col-lg-3">
      <%= f.label :valor, class: 'text-white' %>
      <%= f.search_field :valor_cont, class: 'form-control'%>
    </div>

    <div class="col-lg-3">
      <%= f.label :categoria, class: 'text-white' %>
      <%= f.select :categoria_eq, Produto.categoria, {include_blank: true}, class: "form-control"%>
    </div>

    <div class="col-lg-3">
      <%= f.label :classificacao, class: 'text-white' %>
      <%= f.select :comments_classificacao_eq, Comment.classificacaos, {include_blank: true}, class: "form-control"%>
    </div>
  </div>
  <br/>
  <div class="col-lg-3">
    <%= f.submit "Busca Avançada", class: "btn btn-primary text-white" %>
  </div>
<% end %>

app/views/produtos/edit.js.erb
$(".modal-body").html("<%= j (render 'form') %>")
$("#staticBackdrop").modal("show")

app/views/produtos/index.html.erb
<div class="text-white pt-2">
  <h2></h2>
</div>

<%= render 'search_form' %>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
      <% @produtos.each do |produto| %>
        <% unless produto.archived? %>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" 
                width="100%" height="225" xmlns="http://www.w3.org/2000/svg" 
                role="img" aria-label="Placeholder: Thumbnail" 
                preserveAspectRatio="xMidYMid slice" focusable="false">
                <title><%= produto.nome %></title>
                <rect width="100%" height="100%" fill="#55595c"/>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">
                  <%= link_to produto.nome, produto %>
                  
                </text>
              </svg>
              <div class="card-body">
                <%#= link_to produto.descricao, produto %>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to "View", produto_path(produto), 
                                class: "btn btn-outline-secondary" %>
                    <%= link_to "Edit", edit_produto_path(produto), 
                                class: "btn btn-outline-secondary", remote: true %>

                    <%= link_to "Destroy", produto_path(produto), 
                                class: "btn btn-outline-secondary",
                                method: :delete, 
                                data: {confirm: "Tem Certeza?"} %>
                  </div>
                  <small class="text-muted">Valor: R$<%= produto.valor %></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>  
  </div>
  <br/>    
  <%= link_to 'Novo Produto', new_produto_path, remote:true, class: 'btn btn-primary' %>
</div>

<%= render 'produtos/modal' %>

app/views/produtos/new.js.erb
$(".modal-body").html("<%= j (render 'form') %>")
$("#staticBackdrop").modal("show")

app/views/produtos/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-5 col-md-6 col-12 pb-4 text-white">
        <h1>Produto</h1>
        <div>
          <strong>Codigo:</strong>
          <%= @produto.codigo %>
        </div>
        <br/>
        <div>
          <strong>Valor: R$</strong>
          <%= @produto.valor %>
        </div>
        <br/>
        <div>
          <strong>Nome:</strong>
          <%= @produto.nome %>
        </div>
        <br/>
        <div>
          <strong>Classificação:</strong>
          <%= @produto.classificacao %>
        </div>
        <br/>	
        <div>
          <strong>Descrição:</strong>
          <%= @produto.descricao %> 
        </div>
        <br/>	
        <div>
          <strong>Categoria:</strong>
          <%= @produto.categoria %> 
        </div>
        <br/>
        <div>
          <strong>Imagem:</strong>
          <img src= "<%= @produto.image %>" >
        </div>
        <br/>
        <%= render 'comments/comment', produto: @produto %>  
      </div>
      <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
        <div class="form-group">
          <h4>Deixe um comentário</h4>
          <%= render 'comments/form' %>
        </div>
      </div>
    </div>

    <div class="text-white pt-2">
      <%= link_to "Voltar", root_path, class: "btn btn-primary"%>
    </div>
  </div>
  <br/>
</section>

app/views/shared/_footer.html.erb
<footer class="mt-auto text-white-50">
  <p>
    Rafael dos Santos Galdino 
    <a href="www.linkedin.com/in/rafaeldossantosgaldinosoares" class="text-white">
      RS Company
    </a>, by 
    <a href="www.linkedin.com/in/rafaeldossantosgaldinosoares" class="text-white">
      @2022
    </a>.
  </p>
</footer>

app/views/shared/_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Sobre</h4>
          <p class="text-muted">Website developed by owner Rafael Galdino for language learning.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contato</h4>
          <br/>
          <ul class="list-unstyled">
            <li>
              <a href="https://www.instagram.com/rsgaldinoo/" class="text-white" style="text-decoration:none">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                </svg>
                &nbsp Instagram
              </a>
            </li>
            <br/>
            <li>
              <a href="https://www.facebook.com/" class="text-white" style="text-decoration:none">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
                &nbsp Facebook
              </a>
            </li>
            <br/>
            <li>
              <a href="www.linkedin.com/in/rafaeldossantosgaldinosoares" class="text-white" style="text-decoration:none">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                </svg>
                &nbsp Linkedin
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
          <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
        </svg>
        &nbsp Produtos
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>